name: Bigfoot Report
favicon: null
layout_spectrum: 0.32063
typography_spectrum: 0.005071916850283742
title: The Bigfoot Report
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#908f94'
    - '#171717'
    - '#000000'
    - '#4f4a47'
    - '#716765'
  brandStrength: 1
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
